# Generated by Django 2.1.3 on 2018-11-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('number_of_users', models.IntegerField()),
                ('user_ok', models.IntegerField()),
                ('user_pok', models.IntegerField()),
                ('user_nok', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Country')),
            ],
            options={
                'verbose_name_plural': 'Operators',
            },
        ),
    ]
