# Generated by Django 2.1.3 on 2018-11-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181126_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name_plural': 'Operators'},
        ),
    ]
